from .booru_tagger import NODE_CLASS_MAPPINGS as BOORU_NODE_CLASS_MAPPINGS
from .booru_tagger import NODE_DISPLAY_NAME_MAPPINGS as BOORU_NODE_DISPLAY_NAME_MAPPINGS
from .py.show_text import NODE_CLASS_MAPPINGS as SHOW_TEXT_NODE_CLASS_MAPPINGS
from .py.show_text import NODE_DISPLAY_NAME_MAPPINGS as SHOW_TEXT_NODE_DISPLAY_NAME_MAPPINGS
from .py import autocomplete as _autocomplete  # noqa: F401

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BOORU_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SHOW_TEXT_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BOORU_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SHOW_TEXT_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
